CREATE DATABASE IF NOT EXISTS moti_db;

USE moti_db;

CREATE TABLE IF NOT EXISTS kerkesa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    qyteti VARCHAR(100),
    temperatura FLOAT,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
